# Generated by Django 3.0.3 on 2020-02-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='persons',
            field=models.ManyToManyField(related_name='person_abilities', to='game_objects.Person'),
        ),
        migrations.AddField(
            model_name='ability',
            name='power',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ability',
            name='stamina_points',
            field=models.IntegerField(default=0),
        ),
    ]
