# Generated by Django 2.2.2 on 2020-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_objects', '0002_auto_20200218_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='abilities',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
