# Generated by Django 2.2.2 on 2020-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_objects', '0003_item_abilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='persons',
            field=models.ManyToManyField(null=True, related_name='person_abilities', to='game_objects.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='items',
            field=models.ManyToManyField(null=True, related_name='events', to='game_objects.Item'),
        ),
        migrations.AlterField(
            model_name='event',
            name='persons',
            field=models.ManyToManyField(null=True, related_name='person_events', to='game_objects.Person'),
        ),
    ]
