# Generated by Django 2.2.2 on 2020-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_objects', '0004_auto_20200225_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='fauna',
            field=models.ManyToManyField(null=True, related_name='fauna_places', to='game_objects.Person'),
        ),
        migrations.AlterField(
            model_name='place',
            name='flora',
            field=models.ManyToManyField(null=True, related_name='flora_places', to='game_objects.Person'),
        ),
    ]
