# Generated by Django 2.2.2 on 2019-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('tsp', 'teaspoon'), ('tbl', 'tablespoon'), ('c', 'cup'), ('quart', 'qt'), ('gallon', 'gal'), ('milliliter', 'ml'), ('liter', 'l'), ('deciliter', 'dl'), ('lb', 'pound'), ('oz', 'ounce'), ('g', 'gram'), ('kg', 'kilogram'), ('mm', 'millimeter'), ('cm', 'centimeter'), ('m', 'meter'), ('in', 'inch')], default='', max_length=255, null=True)),
            ],
        ),
    ]
