# Generated by Django 2.2.2 on 2019-08-28 09:37

import accounts.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/victoria/workspace/vuejs_app/vuejs-app/backend/vuejs_app/media/'), upload_to=accounts.models.image_directory_path),
        ),
    ]
